### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

### ISSUE THREAD

**Issue by mathi123** [Odoo-mobile/crm#1]
Steps to reproduce:

1) Open Odoo CRM
2) Add Self-hosted URL
3) Accepts Certificate message
4) Enter other credentials
5) Click Login

Bug:
App hangs on 'Creating account' screen.

![screenshot_2014-08-17-13-43-39](https://cloud.githubusercontent.com/assets/3677437/3944446/158025d0-2604-11e4-8da6-fad0d30e3b90.png)

![screenshot_2014-08-17-13-44-06](https://cloud.githubusercontent.com/assets/3677437/3944451/3c90c4b8-2604-11e4-962b-ac21f40ee03b.png)

![screenshot_2014-08-17-13-44-21](https://cloud.githubusercontent.com/assets/3677437/3944452/3f84af04-2604-11e4-9717-dfdffd21d667.png)

Stacktrace from Logcat:

08-17 13:38:16.423: D/OdooHelper(15306): OHelper->login()
08-17 13:38:16.423: D/odoo.Odoo(15306): https://192.168.1.5
08-17 13:38:16.443: W/System.err(15306): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
08-17 13:38:16.443: W/System.err(15306):    at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
08-17 13:38:16.443: W/System.err(15306):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
08-17 13:38:16.443: W/System.err(15306):    at odoo.Odoo.requestData(Odoo.java:455)
08-17 13:38:16.443: W/System.err(15306):    at odoo.Odoo.getSessionID(Odoo.java:564)
08-17 13:38:16.443: W/System.err(15306):    at odoo.Odoo.init(Odoo.java:360)
08-17 13:38:16.443: W/System.err(15306):    at odoo.Odoo.<init>(Odoo.java:264)
08-17 13:38:16.443: W/System.err(15306):    at com.odoo.orm.OdooHelper.login(OdooHelper.java:47)
08-17 13:38:16.443: W/System.err(15306):    at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:245)
08-17 13:38:16.443: W/System.err(15306):    at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:1)
08-17 13:38:16.443: W/System.err(15306):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-17 13:38:16.443: W/System.err(15306):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-17 13:38:16.443: W/System.err(15306):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-17 13:38:16.443: W/System.err(15306):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-17 13:38:16.443: W/System.err(15306):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-17 13:38:16.443: W/System.err(15306):    at java.lang.Thread.run(Thread.java:841)
08-17 13:38:16.453: W/System.err(15306): java.lang.NullPointerException
08-17 13:38:16.453: W/System.err(15306):    at com.odoo.auth.OdooAccountManager.createAccount(OdooAccountManager.java:96)
08-17 13:38:16.453: W/System.err(15306):    at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:251)
08-17 13:38:16.453: W/System.err(15306):    at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:1)
08-17 13:38:16.453: W/System.err(15306):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-17 13:38:16.453: W/System.err(15306):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-17 13:38:16.453: W/System.err(15306):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-17 13:38:16.453: W/System.err(15306):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-17 13:38:16.453: W/System.err(15306):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-17 13:38:16.453: W/System.err(15306):    at java.lang.Thread.run(Thread.java:841)

**Comment by Jayuda** [comment]
Hello,.. my app also error like that.
This the output :

05-27 11:37:40.285     789-1779/com.odoo D/dalvikvm﹕ GC_FOR_ALLOC freed 0K, 16% free 17263K/20423K, paused 91ms, total 91ms
05-27 11:37:41.285     789-1779/com.odoo E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
05-27 11:37:41.285     789-1779/com.odoo W/System.err﹕ java.lang.RuntimeException: android.os.TransactionTooLargeException
05-27 11:37:41.295     789-1779/com.odoo W/System.err﹕ at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:568)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.auth.OdooAccountManager.createAccount(OdooAccountManager.java:104)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:252)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:225)
05-27 11:37:41.345     789-1779/com.odoo W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-27 11:37:41.345     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
05-27 11:37:41.375     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
05-27 11:37:41.395     789-1779/com.odoo W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
05-27 11:37:41.395     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
05-27 11:37:41.425     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
05-27 11:37:41.435     789-1779/com.odoo W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
05-27 11:37:41.435     789-1779/com.odoo W/System.err﹕ Caused by: android.os.TransactionTooLargeException
05-27 11:37:41.445     789-1779/com.odoo W/System.err﹕ at android.os.BinderProxy.transact(Native Method)
05-27 11:37:41.445     789-1779/com.odoo W/System.err﹕ at android.accounts.IAccountManager$Stub$Proxy.addAccount(IAccountManager.java:579)
05-27 11:37:41.485     789-1779/com.odoo W/System.err﹕ at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:565)
05-27 11:37:41.485     789-1779/com.odoo W/System.err﹕ ... 10 more
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ java.io.IOException: SERVICE_NOT_AVAILABLE
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ at odoo.OdooMobile$1.doInBackground(OdooMobile.java:40)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at odoo.OdooMobile$1.doInBackground(OdooMobile.java:1)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
05-27 11:38:00.064      789-789/com.odoo I/Choreographer﹕ Skipped 35 frames!  The application may be doing too much work on its main thread.

host server use odoo 8.
Please help.
thanks
